version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    # volumes:
    #   - mydata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RootPassw0rd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: Passw0rd
      TZ: Asia/Tokyo
    tty: true
