// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/rema424/twitter-reproduction-backend/database"
	"github.com/rema424/twitter-reproduction-backend/module/twitter/handler"
	"github.com/rema424/twitter-reproduction-backend/repository"
	"github.com/rema424/twitter-reproduction-backend/service"
)

// Injectors from wire.go:

func InitializeHandlers(db database.DB) handler.Factory {
	userRepository := repository.NewUserRepository(db)
	articleRepository := repository.NewArticleRepository(db)
	articleService := service.NewArticleService(userRepository, articleRepository)
	articleHandler := handler.NewArticleHandler(articleService)
	factory := handler.NewFactory(articleHandler)
	return factory
}
