runtime: go
api_version: go1.9

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - .*node_modules
  - .*vendor
  - .*Michael-Inc
  # - ^.*go/src(?!.*twitter-reproduction-backend).*$

handlers:
  - url: /.*
    script: _go_app

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

inbound_services:
  - warmup
